export interface IconDefinition {
  name: string;
  category: string;
  tags: string[];
}

export const ICON_CATEGORIES = [
  'All',
  'Medical & Health',
  'Actions & Controls',
  'Arrows & Direction',
  'Communication & Contact',
  'Trust & Badges',
  'Time & Schedule',
  'Finance & Business',
  'Media & Files',
  'Facilities & Life',
] as const;

export const ICON_CATALOG: IconDefinition[] = [
  // -------------------------------------------------------------
  // Medical & Health (60+ icons)
  // -------------------------------------------------------------
  { name: 'Heart', category: 'Medical & Health', tags: ['love', 'cardiology', 'pulse', 'health', 'organ'] },
  { name: 'HeartPulse', category: 'Medical & Health', tags: ['ecg', 'cardiology', 'pulse', 'monitor', 'vital', 'beat'] },
  { name: 'Activity', category: 'Medical & Health', tags: ['vitals', 'ecg', 'monitor', 'pulse', 'health'] },
  { name: 'Stethoscope', category: 'Medical & Health', tags: ['doctor', 'listen', 'exam', 'clinic', 'auscultation'] },
  { name: 'Cross', category: 'Medical & Health', tags: ['hospital', 'first aid', 'clinic', 'emergency', 'pharmacy'] },
  { name: 'ShieldAlert', category: 'Medical & Health', tags: ['emergency', 'warning', 'critical', 'danger'] },
  { name: 'ShieldCheck', category: 'Medical & Health', tags: ['verified', 'safe', 'protection', 'board certified'] },
  { name: 'ShieldPlus', category: 'Medical & Health', tags: ['health insurance', 'add protection', 'medical cover'] },
  { name: 'Pill', category: 'Medical & Health', tags: ['medicine', 'drug', 'pharmacy', 'prescription', 'tablet'] },
  { name: 'Syringe', category: 'Medical & Health', tags: ['injection', 'vaccine', 'needle', 'blood test', 'infusion'] },
  { name: 'Thermometer', category: 'Medical & Health', tags: ['fever', 'temperature', 'vital', 'heat'] },
  { name: 'Brain', category: 'Medical & Health', tags: ['neurology', 'mind', 'cognition', 'intelligence'] },
  { name: 'Bone', category: 'Medical & Health', tags: ['orthopedics', 'skeleton', 'xray', 'joint'] },
  { name: 'Eye', category: 'Medical & Health', tags: ['vision', 'ophthalmology', 'optometry', 'exam'] },
  { name: 'Ear', category: 'Medical & Health', tags: ['audiology', 'hearing', 'ent', 'exam'] },
  { name: 'Bandage', category: 'Medical & Health', tags: ['first aid', 'wound', 'injury', 'healing'] },
  { name: 'Dna', category: 'Medical & Health', tags: ['genetics', 'science', 'research', 'biology'] },
  { name: 'Ambulance', category: 'Medical & Health', tags: ['paramedic', 'emergency', 'trauma', 'hospital'] },
  { name: 'Hospital', category: 'Medical & Health', tags: ['clinic', 'medical center', 'building', 'healthcare'] },
  { name: 'Microscope', category: 'Medical & Health', tags: ['lab', 'pathology', 'science', 'investigation'] },
  { name: 'TestTube', category: 'Medical & Health', tags: ['blood work', 'lab', 'diagnostics', 'specimen'] },
  { name: 'FlaskConical', category: 'Medical & Health', tags: ['chemistry', 'pharmacology', 'research'] },
  { name: 'Droplets', category: 'Medical & Health', tags: ['blood', 'plasma', 'hydration', 'liquid'] },
  { name: 'HeartHandshake', category: 'Medical & Health', tags: ['compassion', 'care', 'advocacy', 'partner', 'trust'] },
  { name: 'UserCheck', category: 'Medical & Health', tags: ['patient verified', 'doctor approved', 'appointment'] },
  { name: 'Smile', category: 'Medical & Health', tags: ['pediatrics', 'mental health', 'satisfaction', 'happy'] },
  { name: 'Accessibility', category: 'Medical & Health', tags: ['handicap', 'wheelchair', 'accessible', 'mobility'] },
  { name: 'Baby', category: 'Medical & Health', tags: ['pediatrics', 'infant', 'obstetrics', 'neonatal'] },
  { name: 'Apple', category: 'Medical & Health', tags: ['nutrition', 'diet', 'wellness', 'cardiac diet'] },
  { name: 'Salad', category: 'Medical & Health', tags: ['healthy eating', 'nutrition', 'dietitian', 'lifestyle'] },
  { name: 'Scale', category: 'Medical & Health', tags: ['weight', 'bmi', 'measurement', 'metabolic'] },
  { name: 'Weight', category: 'Medical & Health', tags: ['bariatric', 'fitness', 'exercise', 'mass'] },
  { name: 'Footprints', category: 'Medical & Health', tags: ['podiatry', 'cardiac rehab', 'walking', 'steps'] },
  { name: 'HeartCrack', category: 'Medical & Health', tags: ['infarction', 'attack', 'emergency', 'pain'] },
  { name: 'Sparkles', category: 'Medical & Health', tags: ['clean', 'sterile', 'longevity', 'vip care'] },
  { name: 'Radiation', category: 'Medical & Health', tags: ['imaging', 'radiology', 'ct scan', 'xray'] },
  { name: 'AlarmClockCheck', category: 'Medical & Health', tags: ['medication reminder', 'fasting', 'on time'] },

  // -------------------------------------------------------------
  // Actions & Controls (90+ icons)
  // -------------------------------------------------------------
  { name: 'Plus', category: 'Actions & Controls', tags: ['add', 'create', 'new', 'more'] },
  { name: 'PlusCircle', category: 'Actions & Controls', tags: ['add item', 'new appointment', 'insert'] },
  { name: 'Minus', category: 'Actions & Controls', tags: ['remove', 'decrease', 'less'] },
  { name: 'MinusCircle', category: 'Actions & Controls', tags: ['delete', 'remove', 'strip'] },
  { name: 'Check', category: 'Actions & Controls', tags: ['confirm', 'done', 'yes', 'verified'] },
  { name: 'CheckCheck', category: 'Actions & Controls', tags: ['double check', 'delivered', 'read'] },
  { name: 'CheckCircle', category: 'Actions & Controls', tags: ['success', 'completed', 'approved'] },
  { name: 'CheckCircle2', category: 'Actions & Controls', tags: ['certified', 'passed', 'healthy'] },
  { name: 'X', category: 'Actions & Controls', tags: ['close', 'cancel', 'dismiss', 'delete'] },
  { name: 'XCircle', category: 'Actions & Controls', tags: ['decline', 'stop', 'failed', 'cancel'] },
  { name: 'Trash2', category: 'Actions & Controls', tags: ['delete', 'remove', 'garbage', 'bin'] },
  { name: 'Edit', category: 'Actions & Controls', tags: ['modify', 'write', 'change', 'pen'] },
  { name: 'Edit2', category: 'Actions & Controls', tags: ['pencil', 'author', 'customize'] },
  { name: 'Edit3', category: 'Actions & Controls', tags: ['signature', 'write', 'update'] },
  { name: 'PenTool', category: 'Actions & Controls', tags: ['signature', 'design', 'vector'] },
  { name: 'Pencil', category: 'Actions & Controls', tags: ['sketch', 'record', 'notes'] },
  { name: 'Sliders', category: 'Actions & Controls', tags: ['filters', 'adjust', 'tweak', 'settings'] },
  { name: 'SlidersHorizontal', category: 'Actions & Controls', tags: ['controls', 'levels', 'adjustments'] },
  { name: 'Filter', category: 'Actions & Controls', tags: ['sort', 'refine', 'funnel', 'search'] },
  { name: 'Search', category: 'Actions & Controls', tags: ['find', 'lookup', 'explore', 'query'] },
  { name: 'ZoomIn', category: 'Actions & Controls', tags: ['magnify', 'enlarge', 'inspect'] },
  { name: 'ZoomOut', category: 'Actions & Controls', tags: ['shrink', 'scale down', 'overview'] },
  { name: 'Copy', category: 'Actions & Controls', tags: ['duplicate', 'clipboard', 'clone'] },
  { name: 'Save', category: 'Actions & Controls', tags: ['store', 'record', 'disk', 'publish'] },
  { name: 'Download', category: 'Actions & Controls', tags: ['pdf', 'records', 'save file', 'export'] },
  { name: 'Upload', category: 'Actions & Controls', tags: ['import', 'upload image', 'attachment'] },
  { name: 'Share2', category: 'Actions & Controls', tags: ['social', 'forward', 'send out'] },
  { name: 'ExternalLink', category: 'Actions & Controls', tags: ['open in new tab', 'url', 'website', 'jump'] },
  { name: 'Link', category: 'Actions & Controls', tags: ['hyperlink', 'url', 'chain', 'connect'] },
  { name: 'Link2', category: 'Actions & Controls', tags: ['web address', 'connect', 'attachment'] },
  { name: 'RotateCw', category: 'Actions & Controls', tags: ['rotate right', 'turn', 'clockwise'] },
  { name: 'RotateCcw', category: 'Actions & Controls', tags: ['undo', 'rotate left', 'counter clockwise'] },
  { name: 'RefreshCw', category: 'Actions & Controls', tags: ['sync', 'reload', 'update', 'fetch'] },
  { name: 'RefreshCcw', category: 'Actions & Controls', tags: ['revert', 'retry', 'restart'] },
  { name: 'Power', category: 'Actions & Controls', tags: ['on', 'off', 'toggle', 'switch'] },
  { name: 'Maximize', category: 'Actions & Controls', tags: ['fullscreen', 'expand', 'zoom'] },
  { name: 'Minimize', category: 'Actions & Controls', tags: ['collapse', 'shrink', 'exit fullscreen'] },
  { name: 'Maximize2', category: 'Actions & Controls', tags: ['expand window', 'larger view'] },
  { name: 'Minimize2', category: 'Actions & Controls', tags: ['compress view', 'compact'] },
  { name: 'MoreHorizontal', category: 'Actions & Controls', tags: ['menu', 'options', 'dots'] },
  { name: 'MoreVertical', category: 'Actions & Controls', tags: ['context menu', 'actions'] },
  { name: 'Menu', category: 'Actions & Controls', tags: ['hamburger', 'drawer', 'sidebar'] },
  { name: 'Grid', category: 'Actions & Controls', tags: ['gallery', 'tiles', 'cards', 'bento'] },
  { name: 'List', category: 'Actions & Controls', tags: ['directory', 'bullet', 'index'] },
  { name: 'Layout', category: 'Actions & Controls', tags: ['template', 'page builder', 'sections'] },
  { name: 'Layers', category: 'Actions & Controls', tags: ['stack', 'components', 'levels'] },
  { name: 'Settings', category: 'Actions & Controls', tags: ['preferences', 'gear', 'configuration'] },
  { name: 'ScanEye', category: 'Actions & Controls', tags: ['scanner', 'retina', 'visible', 'preview', 'show'] },
  { name: 'EyeOff', category: 'Actions & Controls', tags: ['hidden', 'conceal', 'mask'] },
  { name: 'Wrench', category: 'Actions & Controls', tags: ['tools', 'service', 'maintenance'] },
  { name: 'Sparkle', category: 'Actions & Controls', tags: ['star', 'accent', 'ai', 'magic'] },
  { name: 'Zap', category: 'Actions & Controls', tags: ['instant', 'fast', 'lightning', 'energy'] },

  // -------------------------------------------------------------
  // Arrows & Direction (60+ icons)
  // -------------------------------------------------------------
  { name: 'ArrowRight', category: 'Arrows & Direction', tags: ['next', 'proceed', 'forward', 'cta'] },
  { name: 'ArrowLeft', category: 'Arrows & Direction', tags: ['back', 'previous', 'return'] },
  { name: 'ArrowUp', category: 'Arrows & Direction', tags: ['top', 'ascend', 'scroll up'] },
  { name: 'ArrowDown', category: 'Arrows & Direction', tags: ['bottom', 'descend', 'scroll down'] },
  { name: 'ArrowUpRight', category: 'Arrows & Direction', tags: ['external', 'jump', 'outbound'] },
  { name: 'ArrowDownRight', category: 'Arrows & Direction', tags: ['expand', 'drill down'] },
  { name: 'ChevronRight', category: 'Arrows & Direction', tags: ['next', 'accordion', 'slide'] },
  { name: 'ChevronLeft', category: 'Arrows & Direction', tags: ['prev', 'back'] },
  { name: 'ChevronDown', category: 'Arrows & Direction', tags: ['dropdown', 'open', 'more'] },
  { name: 'ChevronUp', category: 'Arrows & Direction', tags: ['collapse', 'close'] },
  { name: 'ChevronsRight', category: 'Arrows & Direction', tags: ['fast forward', 'skip'] },
  { name: 'ChevronsLeft', category: 'Arrows & Direction', tags: ['rewind', 'start'] },
  { name: 'CornerDownRight', category: 'Arrows & Direction', tags: ['sub-item', 'reply', 'indent'] },
  { name: 'CornerUpRight', category: 'Arrows & Direction', tags: ['forward', 'redirect'] },
  { name: 'MoveRight', category: 'Arrows & Direction', tags: ['shift', 'drag', 'next step'] },
  { name: 'Compass', category: 'Arrows & Direction', tags: ['direction', 'orientation', 'guide'] },
  { name: 'Navigation', category: 'Arrows & Direction', tags: ['gps', 'directions', 'drive to clinic'] },
  { name: 'MapPin', category: 'Arrows & Direction', tags: ['location', 'address', 'suite', 'hospital'] },
  { name: 'Map', category: 'Arrows & Direction', tags: ['geography', 'city', 'find office'] },
  { name: 'Route', category: 'Arrows & Direction', tags: ['path', 'directions', 'transit'] },
  { name: 'Milestone', category: 'Arrows & Direction', tags: ['signpost', 'distance', 'goal'] },
  { name: 'Locate', category: 'Arrows & Direction', tags: ['gps', 'find me', 'current position'] },
  { name: 'LocateFixed', category: 'Arrows & Direction', tags: ['pinned location', 'gps lock'] },

  // -------------------------------------------------------------
  // Communication & Contact (60+ icons)
  // -------------------------------------------------------------
  { name: 'Phone', category: 'Communication & Contact', tags: ['call', 'telephone', 'mobile', 'hotline'] },
  { name: 'PhoneCall', category: 'Communication & Contact', tags: ['active call', 'speak with doctor', 'reception'] },
  { name: 'PhoneForwarded', category: 'Communication & Contact', tags: ['transfer', 'answering service', 'nurse line'] },
  { name: 'PhoneIncoming', category: 'Communication & Contact', tags: ['inbound', 'triage', 'call back'] },
  { name: 'Mail', category: 'Communication & Contact', tags: ['email', 'letter', 'inbox', 'message'] },
  { name: 'MailCheck', category: 'Communication & Contact', tags: ['confirmed email', 'delivered appointment'] },
  { name: 'MailOpen', category: 'Communication & Contact', tags: ['read message', 'notification opened'] },
  { name: 'MailPlus', category: 'Communication & Contact', tags: ['new inquiry', 'compose email'] },
  { name: 'MessageSquare', category: 'Communication & Contact', tags: ['chat', 'review', 'comment', 'feedback'] },
  { name: 'MessageCircle', category: 'Communication & Contact', tags: ['sms', 'chat bubble', 'patient portal'] },
  { name: 'MessagesSquare', category: 'Communication & Contact', tags: ['discussion', 'consultation notes'] },
  { name: 'Send', category: 'Communication & Contact', tags: ['submit', 'dispatch', 'paper airplane'] },
  { name: 'Inbox', category: 'Communication & Contact', tags: ['patient intake', 'mailbox', 'leads'] },
  { name: 'AtSign', category: 'Communication & Contact', tags: ['mention', 'email', 'handle'] },
  { name: 'Globe', category: 'Communication & Contact', tags: ['website', 'international', 'worldwide', 'internet'] },
  { name: 'Wifi', category: 'Communication & Contact', tags: ['patient internet', 'telemedicine', 'connectivity'] },
  { name: 'Radio', category: 'Communication & Contact', tags: ['broadcast', 'telemetry', 'frequency'] },
  { name: 'Headphones', category: 'Communication & Contact', tags: ['audio consult', 'telehealth', 'support'] },
  { name: 'Mic', category: 'Communication & Contact', tags: ['dictation', 'voice recording', 'speech'] },
  { name: 'Bell', category: 'Communication & Contact', tags: ['reminder', 'alert', 'notification'] },
  { name: 'BellRing', category: 'Communication & Contact', tags: ['active reminder', 'ringing'] },
  { name: 'Megaphone', category: 'Communication & Contact', tags: ['announcement', 'public health notice', 'broadcast'] },
  { name: 'Contact', category: 'Communication & Contact', tags: ['business card', 'address book', 'directory'] },
  { name: 'Users', category: 'Communication & Contact', tags: ['clinical team', 'patient family', 'staff'] },
  { name: 'UserPlus', category: 'Communication & Contact', tags: ['new patient registration', 'add contact'] },

  // -------------------------------------------------------------
  // Trust, Security & Badges (50+ icons)
  // -------------------------------------------------------------
  { name: 'Shield', category: 'Trust & Badges', tags: ['security', 'hipaa', 'confidential', 'safe'] },
  { name: 'Lock', category: 'Trust & Badges', tags: ['secure', 'encrypted', 'private', 'password'] },
  { name: 'Unlock', category: 'Trust & Badges', tags: ['open access', 'portal unlocked'] },
  { name: 'Key', category: 'Trust & Badges', tags: ['credentials', 'access', 'passcode'] },
  { name: 'Award', category: 'Trust & Badges', tags: ['fellowship', 'diploma', 'board certified', 'honor'] },
  { name: 'Medal', category: 'Trust & Badges', tags: ['excellence', 'top doctor', 'ranking'] },
  { name: 'Trophy', category: 'Trust & Badges', tags: ['best in practice', 'achievement', 'first place'] },
  { name: 'Crown', category: 'Trust & Badges', tags: ['premier', 'vip patient', 'leader in cardiology'] },
  { name: 'Star', category: 'Trust & Badges', tags: ['rating', '5 stars', 'favorite', 'testimonial'] },
  { name: 'StarHalf', category: 'Trust & Badges', tags: ['rating partial', 'reviews'] },
  { name: 'BadgeCheck', category: 'Trust & Badges', tags: ['verified specialist', 'board accredited'] },
  { name: 'BadgeAlert', category: 'Trust & Badges', tags: ['license advisory', 'notice'] },
  { name: 'BadgePercent', category: 'Trust & Badges', tags: ['satisfaction rate', 'guarantee'] },
  { name: 'FileCheck', category: 'Trust & Badges', tags: ['approved chart', 'verified records'] },
  { name: 'Fingerprint', category: 'Trust & Badges', tags: ['biometric', 'hipaa secure', 'identity'] },
  { name: 'FileLock', category: 'Trust & Badges', tags: ['confidential chart', 'encrypted record'] },
  { name: 'CheckSquare', category: 'Trust & Badges', tags: ['accredited', 'verified', 'standard met', 'approved checkbox'] },

  // -------------------------------------------------------------
  // Time, Calendar & Scheduling (40+ icons)
  // -------------------------------------------------------------
  { name: 'Calendar', category: 'Time & Schedule', tags: ['appointment', 'schedule', 'booking', 'date'] },
  { name: 'CalendarDays', category: 'Time & Schedule', tags: ['operating hours', 'clinic days', 'events'] },
  { name: 'CalendarCheck', category: 'Time & Schedule', tags: ['confirmed appointment', 'booking verified'] },
  { name: 'CalendarClock', category: 'Time & Schedule', tags: ['slot reservation', 'consultation time'] },
  { name: 'CalendarHeart', category: 'Time & Schedule', tags: ['cardiac checkup', 'wellness exam date'] },
  { name: 'CalendarPlus', category: 'Time & Schedule', tags: ['schedule new visit', 'add to calendar'] },
  { name: 'Clock', category: 'Time & Schedule', tags: ['hours', 'duration', 'time', 'punctual'] },
  { name: 'Hourglass', category: 'Time & Schedule', tags: ['wait time', 'turnaround', 'processing'] },
  { name: 'Timer', category: 'Time & Schedule', tags: ['procedure duration', 'countdown', 'speed'] },
  { name: 'TimerReset', category: 'Time & Schedule', tags: ['reschedule', 'restart timer'] },
  { name: 'Watch', category: 'Time & Schedule', tags: ['continuous monitor', 'smartwatch ecg'] },
  { name: 'History', category: 'Time & Schedule', tags: ['patient history', 'medical records past', 'logs'] },
  { name: 'AlarmClock', category: 'Time & Schedule', tags: ['reminder', 'morning meds', 'wake up'] },

  // -------------------------------------------------------------
  // Finance & Business (50+ icons)
  // -------------------------------------------------------------
  { name: 'CreditCard', category: 'Finance & Business', tags: ['payment', 'consultation fee', 'visa', 'mastercard'] },
  { name: 'Wallet', category: 'Finance & Business', tags: ['co-pay', 'billing', 'hsa', 'fsa'] },
  { name: 'Banknote', category: 'Finance & Business', tags: ['cash', 'currency', 'direct billing'] },
  { name: 'DollarSign', category: 'Finance & Business', tags: ['pricing', 'procedure cost', 'quote'] },
  { name: 'Coins', category: 'Finance & Business', tags: ['insurance contribution', 'savings'] },
  { name: 'Receipt', category: 'Finance & Business', tags: ['itemized bill', 'superbill', 'invoice'] },
  { name: 'Tag', category: 'Finance & Business', tags: ['specialty badge', 'category', 'label'] },
  { name: 'Tags', category: 'Finance & Business', tags: ['procedure tags', 'keywords'] },
  { name: 'Percent', category: 'Finance & Business', tags: ['discount', 'coverage percent', 'success rate'] },
  { name: 'Calculator', category: 'Finance & Business', tags: ['cardiac risk calculator', 'framingham', 'estimate'] },
  { name: 'TrendingUp', category: 'Finance & Business', tags: ['health improvement', 'recovery trajectory', 'growth'] },
  { name: 'TrendingDown', category: 'Finance & Business', tags: ['blood pressure reduction', 'cholesterol drop'] },
  { name: 'BarChart', category: 'Finance & Business', tags: ['clinical statistics', 'outcomes', 'research data'] },
  { name: 'BarChart2', category: 'Finance & Business', tags: ['metrics', 'benchmark', 'hospital rank'] },
  { name: 'PieChart', category: 'Finance & Business', tags: ['demographics', 'distribution'] },
  { name: 'LineChart', category: 'Finance & Business', tags: ['vitals over time', 'holter monitor graph'] },
  { name: 'Briefcase', category: 'Finance & Business', tags: ['practice management', 'executive physical'] },
  { name: 'Building', category: 'Finance & Business', tags: ['medical center', 'hospital wing', 'facility'] },
  { name: 'Building2', category: 'Finance & Business', tags: ['clinic tower', 'plaza', 'campus'] },
  { name: 'Landmark', category: 'Finance & Business', tags: ['university hospital', 'academic medical center'] },

  // -------------------------------------------------------------
  // Media & Files (60+ icons)
  // -------------------------------------------------------------
  { name: 'Image', category: 'Media & Files', tags: ['photo', 'headshot', 'picture', 'xray'] },
  { name: 'Images', category: 'Media & Files', tags: ['gallery', 'facility tour', 'suite pictures'] },
  { name: 'Camera', category: 'Media & Files', tags: ['take picture', 'dermascope', 'capture'] },
  { name: 'Video', category: 'Media & Files', tags: ['telemedicine video', 'ultrasound clip', 'procedure'] },
  { name: 'Film', category: 'Media & Files', tags: ['angiography loop', 'fluoroscopy', 'cath lab film'] },
  { name: 'Play', category: 'Media & Files', tags: ['play video', 'procedure animation'] },
  { name: 'PlayCircle', category: 'Media & Files', tags: ['watch patient testimonial', 'video consult'] },
  { name: 'Pause', category: 'Media & Files', tags: ['pause playback'] },
  { name: 'File', category: 'Media & Files', tags: ['document', 'clinical report', 'intake form'] },
  { name: 'FileText', category: 'Media & Files', tags: ['medical chart', 'prescription', 'referral'] },
  { name: 'Files', category: 'Media & Files', tags: ['patient records', 'bundle', 'documents'] },
  { name: 'Folder', category: 'Media & Files', tags: ['case file', 'directory', 'archives'] },
  { name: 'FolderPlus', category: 'Media & Files', tags: ['new patient chart', 'create folder'] },
  { name: 'FolderOpen', category: 'Media & Files', tags: ['browse files', 'opened records'] },
  { name: 'Archive', category: 'Media & Files', tags: ['stored charts', 'historical records'] },
  { name: 'Paperclip', category: 'Media & Files', tags: ['attach lab report', 'ecg pdf attachment'] },
  { name: 'Scissors', category: 'Media & Files', tags: ['surgery', 'procedure', 'incision'] },
  { name: 'Printer', category: 'Media & Files', tags: ['print summary', 'orders', 'rx print'] },
  { name: 'Book', category: 'Media & Files', tags: ['medical textbook', 'cardiology guidelines', 'journal'] },
  { name: 'BookOpen', category: 'Media & Files', tags: ['patient education handbook', 'read article'] },
  { name: 'Bookmark', category: 'Media & Files', tags: ['save doctor', 'pin service'] },
  { name: 'Notebook', category: 'Media & Files', tags: ['clinical journal', 'fellowship notes'] },
  { name: 'Presentation', category: 'Media & Files', tags: ['medical lecture', 'keynote', 'symposium'] },

  // -------------------------------------------------------------
  // Facilities & Life (40+ icons)
  // -------------------------------------------------------------
  { name: 'Coffee', category: 'Facilities & Life', tags: ['lounge', 'waiting room', 'amenity'] },
  { name: 'Car', category: 'Facilities & Life', tags: ['valet', 'parking lot', 'drive'] },
  { name: 'Bus', category: 'Facilities & Life', tags: ['public transit', 'subway', 'bus line'] },
  { name: 'Plane', category: 'Facilities & Life', tags: ['medical tourism', 'out of state patients', 'travel'] },
  { name: 'Train', category: 'Facilities & Life', tags: ['commuter rail', 'amtrak', 'station near clinic'] },
  { name: 'Home', category: 'Facilities & Life', tags: ['home visit', 'discharge', 'residential care'] },
  { name: 'Bed', category: 'Facilities & Life', tags: ['inpatient', 'recovery suite', 'admission'] },
  { name: 'Hotel', category: 'Facilities & Life', tags: ['patient lodging', 'accommodations near hospital'] },
  { name: 'Utensils', category: 'Facilities & Life', tags: ['nutrition', 'cafeteria', 'cardiac diet'] },
  { name: 'Sun', category: 'Facilities & Life', tags: ['morning hours', 'vitamin d', 'light mode'] },
  { name: 'Moon', category: 'Facilities & Life', tags: ['on-call night service', 'sleep apnea', 'dark mode'] },
  { name: 'Cloud', category: 'Facilities & Life', tags: ['cloud storage', 'telemetry data', 'weather'] },
  { name: 'Umbrella', category: 'Facilities & Life', tags: ['insurance umbrella', 'protection', 'coverage'] },
  { name: 'Wind', category: 'Facilities & Life', tags: ['pulmonology', 'respiratory', 'air quality', 'asthma'] },
  { name: 'Trees', category: 'Facilities & Life', tags: ['healing garden', 'sanctuary', 'peaceful'] },
  { name: 'Flower', category: 'Facilities & Life', tags: ['holistic wellness', 'recovery', 'comfort'] },
  { name: 'Leaf', category: 'Facilities & Life', tags: ['organic nutrition', 'plant based lifestyle'] },
];

export const TOTAL_ICONS_COUNT = ICON_CATALOG.length;
